settings:
  browser_thread: 5 #Enter Browser Thread
  use_proxy: False # True / False
  proxy_protocol: "HTTP" # HTTP / SOCKS5
  account_count: 10 # JUMLAH AKUN YANG INGIN ANDA HASILKAN
  api_key: "" # SMSACTIVE API KEY
